default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: cafe  # 실제 mysql에 생성되는 database 이름
  pool: 5
  username: cafe    # mysql에 접속할 id와 password
  password: cafe
  socket: /tmp/mysql.sock # 보통 mysql.sock은 tmp에 있다. (시스템에 따라..)
  
test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3

###########################

ora_db: &default
  adapter: oracle_enhanced    #사용할 database
  reconnect: false
  database: samilnet.com:1522/ora10
  pool: 5
  username: samil3    # mysql에 접속할 id와 password
  password: samil03
  
